services:
    # Application services

    server:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        command: python /application/server.py
        restart: unless-stopped
        ports:
            - 80:8080
        volumes:
            # Mount persistent volume
            - data:/data
        environment:
            # Address to redis instance
            - REDIS=redis://redis/

    worker:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        command: python /application/worker.py
        restart: unless-stopped
        volumes:
            # Mount persistent volume
            - data:/data
        environment:
            # Address to redis instance
            - REDIS=redis://redis/

    # Database service

    redis:
        image: redis:7.4.0-alpine
        command: --save 300 1
        restart: unless-stopped
        volumes:
            # Mount persistent volume
            - redis:/data

volumes:
    # Persistent volume for server and worker
    data: {}

    # Persistent volume for database
    redis: {}
