version: "3"

# Configure applcation service
services: 
    application:
        build: application
        restart: unless-stopped
        ports: 
            - 80:80
            - 443:443
        volumes:
            # Data volume path
            - data:/data
        environment:
            # Address to redis instance
            - REDIS=redis://redis/
    
    redis:
        image: redis:7.4.0-alpine
        command: --save 300 1
        restart: unless-stopped
        volumes:
            # Data volume path
            - data:/data

# Configure persistent data volume
volumes:
    data: