services:
    # Application service

    server:
        image: webhood/3.10
        command: python /application/server.py
        restart: unless-stopped
        ports:
            - 80:8080
        volumes:
            # Sources mounts
            - ./src/backend:/application/backend:ro
            - ./src/frontend/index.html:/application/frontend/index.html:ro
            - ./src/frontend/application:/application/frontend/application:ro
            # Mount persistent volume
            - data:/data
        environment:
            # Address to redis instance
            - REDIS=redis://redis/

    worker:
        image: webhood/3.10
        command: python /application/worker.py
        restart: unless-stopped
        volumes:
            # Sources mounts
            - ./src/backend:/application/backend:ro
            - ./src/frontend/index.html:/application/frontend/index.html:ro
            - ./src/frontend/application:/application/frontend/application:ro
            # Mount persistent volume
            - data:/data
        environment:
            # Address to redis instance
            - REDIS=redis://redis/

    # Database service

    redis:
        image: redis:7.4.0-alpine
        command: --save 300 1
        restart: unless-stopped
        volumes:
            # Mount persistent volume
            - redis:/data

volumes:
    # Persistent volume for server and worker
    data: {}

    # Persistent volume for database
    redis: {}
