services:
    # Application service

    application:
        image: webhood/3.10
        restart: unless-stopped
        ports:
            - 80:8080
            - 443:8443
        volumes:
            # Sources mounts
            - ./src/backend/app.py:/application/backend/app.py:ro
            - ./src/backend/worker.py:/application/backend/worker.py:ro
            - ./src/frontend/index.html:/application/frontend/index.html:ro
            - ./src/frontend/application:/application/frontend/application:ro
            # Mount persistent volume
            - application:/data
        environment:
            # Address to redis instance
            - REDIS=redis://redis/

    # Database service

    redis:
        image: redis:7.4.0-alpine
        command: --save 300 1
        restart: unless-stopped
        volumes:
            # Mount persistent volume
            - redis:/data

volumes:
    # Persistent volume for database
    redis: {}

    # Persistent volume for application
    application: {}
