version: "3"

# Configure applcation service
services: 
    application:
        image: webhood/3.8
        restart: unless-stopped
        ports: 
            - 80:80
            - 443:443
        volumes:
            # Sources mounts
            - ./src/backend/app.py:/application/backend/app.py:ro
            - ./src/backend/worker.py:/application/backend/worker.py:ro
            - ./src/frontend/index.html:/application/frontend/index.html:ro
            - ./src/frontend/application:/application/frontend/application:ro
            # Configuration mounts
            - ./configurations/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - ./configurations/entrypoint.conf:/etc/entrypoint/conf.d/entrypoint.conf:ro
            # Data volume path
            - data:/opt

# Configure persistent data volume
volumes:
    data: