# Select compose version
version: "3"

# Define services
services: 
    # Create template service
    application:
        # Select service image
        build: application
        
        # Restart policy
        restart: unless-stopped
        
        # Expose ports
        ports: 
            - 80:80

        # Mount volumes
        volumes:
            # Persistent data volume
            - data:/opt

volumes:
    data: