# Select compose version
version: "3"

# Define services
services: 
    # Create template service
    application:
        # Select service image
        build: template
        
        # Expose ports
        ports: 
            - 8000:80
            - 8001:443